apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "log-processing-system.fullname" . }}-config
  labels:
    {{- include "log-processing-system.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ include "log-processing-system.kafkaBootstrapServers" . | quote }}
  KAFKA_HEALTH_TIMEOUT_SECONDS: {{ .Values.healthCheck.timeoutSeconds | quote }}
  KAFKA_TOPICS: {{ range $i, $t := .Values.topics }}{{ if $i }},{{ end }}{{ $t.name }}{{ end }}
